channels:
- conda-forge
dependencies:
- python=3.9.1
- pip<=23.2.1
- pip:
  - mlflow==2.22.2
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.3.2
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
